/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Fabian Aguila
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario() {
        initComponents();
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon("C:/Users/FaleTala/Pictures/cine5.jpg");
        JLabel fondo= new JLabel(); fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldRut = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jPasswordFieldConfContraseña = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlblEstadoContraseña = new javax.swing.JLabel();
        jlblEstadoRut = new javax.swing.JLabel();
        jlblEstadoContraseñasIguales = new javax.swing.JLabel();
        jLabelValidarEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirma contraseña");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rut");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");

        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyTyped(evt);
            }
        });

        jTextFieldRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRutFocusLost(evt);
            }
        });
        jTextFieldRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldRutKeyTyped(evt);
            }
        });

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyTyped(evt);
            }
        });

        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusLost(evt);
            }
        });
        jPasswordFieldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseñaKeyTyped(evt);
            }
        });

        jPasswordFieldConfContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldConfContraseñaFocusLost(evt);
            }
        });
        jPasswordFieldConfContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordFieldConfContraseñaKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/registrar2424.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close2424.png"))); // NOI18N
        jButton2.setText("Cancelar");

        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recycle2424.png"))); // NOI18N
        jButton3.setText("Limpiar Formulario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/movies.png"))); // NOI18N

        jlblEstadoContraseña.setText(" ");

        jlblEstadoRut.setText(" ");

        jlblEstadoContraseñasIguales.setText(" ");

        jLabelValidarEmail.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelValidarEmail)
                            .addComponent(jlblEstadoContraseñasIguales)
                            .addComponent(jlblEstadoContraseña)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldUsuario)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jPasswordFieldContraseña)
                                    .addComponent(jPasswordFieldConfContraseña)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblEstadoRut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblEstadoRut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblEstadoContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldConfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblEstadoContraseñasIguales)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValidarEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarUsuarios();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            registrarUsuarios();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jTextFieldRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRutFocusLost
        if(validarRut())
        {
            this.jlblEstadoRut.setForeground(Color.white);
            this.jlblEstadoRut.setText("Rut válido");
        }
        else
        {
            this.jlblEstadoRut.setForeground(Color.yellow);
            this.jlblEstadoRut.setText("Rut Inválido");
        }
    }//GEN-LAST:event_jTextFieldRutFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Login().configAccesoLoginUsuario();
    }//GEN-LAST:event_formWindowClosing

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ReestablecerFormularioRegistroDeUsuario();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordFieldConfContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConfContraseñaFocusLost
        validarIgualdadContraseñas();
    }//GEN-LAST:event_jPasswordFieldConfContraseñaFocusLost

    private void jTextFieldRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRutKeyTyped
        char caracter = evt.getKeyChar();
        if(! (Character.isDigit(caracter) || caracter == KeyEvent.VK_MINUS
            || caracter == 'k' || caracter == 'K'))
        {
            evt.consume();
        }
        if (this.jTextFieldRut.getText().length() == 12)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldRutKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (! (Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE))
        {
            evt.consume();
        }
        if (this.jTextFieldNombre.getText().length() == 40)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (validarEmail(jTextFieldEmail.getText()))
        {
            this.jLabelValidarEmail.setForeground(Color.white);
            this.jLabelValidarEmail.setText("Email válido");
        }
        else
        {
            this.jLabelValidarEmail.setForeground(Color.yellow);
            this.jLabelValidarEmail.setText("Email Inválido");
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jPasswordFieldContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusLost
       validarContraseñaLetrasyNumeros();
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusLost

    private void jTextFieldUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyTyped
        if (this.jTextFieldUsuario.getText().length() == 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldUsuarioKeyTyped

    private void jPasswordFieldContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaKeyTyped
        if (this.jPasswordFieldContraseña.getPassword().length == 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldContraseñaKeyTyped

    private void jPasswordFieldConfContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldConfContraseñaKeyTyped
        if (this.jPasswordFieldConfContraseña.getPassword().length == 20)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jPasswordFieldConfContraseñaKeyTyped

    private void jTextFieldEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyTyped
        if (this.jTextFieldEmail.getText().length() == 40)
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldEmailKeyTyped
    
    private boolean validarIgualdadContraseñas(){
        char[] pw1 = jPasswordFieldContraseña.getPassword();
        char[] pw2 = jPasswordFieldConfContraseña.getPassword();
        String pass1 = new String(pw1);
        String pass2 = new String(pw2);
        if (pass1.equals("") || pass2.equals("")) 
        {
            jlblEstadoContraseñasIguales.setForeground(Color.yellow);
            jlblEstadoContraseñasIguales.setText("Campo(s) vacio(s)");
            return false;
        }
        else 
        {
            if (pass1.equals(pass2))
            {
                jlblEstadoContraseñasIguales.setForeground(Color.white);
                jlblEstadoContraseñasIguales.setText("Ok");
                return true;
            } 
            else 
            {
                if(pass2.length() < 6)
                {       
                jlblEstadoContraseñasIguales.setForeground(Color.yellow);
                jlblEstadoContraseñasIguales.setText("minimo 6 caracteres");
                return false;
                }
                else
                {
                jlblEstadoContraseñasIguales.setForeground(Color.yellow);
                jlblEstadoContraseñasIguales.setText("Las contraseñas no coinciden");
                return false;
                }    
            }
        }
    }
    
    private void registrarUser(){
        try
        {
            /* captura usuario*/
            String nuevoUser = this.jTextFieldUsuario.getText();
            if(nuevoUser.length() == 0)
            {
                nuevoUser = null;
            }
            /*captura de contraseña*/
            char[] pw = this.jPasswordFieldContraseña.getPassword();
            String pwNuevoUser = new String(pw);
            if (pwNuevoUser.length() == 0)
            {
                pwNuevoUser = null;
            } 
            /* caputa rut*/
            String rutDV = this.jTextFieldRut.getText();
            int rut = Integer.parseInt(rutDV.substring(0,rutDV.length() - 2));
            /*captura nombre*/
            String nombre = this.jTextFieldNombre.getText().trim();
            if(nombre.length() == 0)
            {
                nombre = null;
            }
            /*captura de Email*/
            String email = this.jTextFieldEmail.getText().trim();
            if(email.length() == 0)
            {
                email = null;
            }

            /*int resultado = new BLL.Usuario().registrarUsuarioBLL(nuevoUser,pwNuevoUser,rut,nombre,email);
            switch(resultado)
            {
                case 1: JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente", "Registros", JOptionPane.INFORMATION_MESSAGE);
                            this.dispose();
                            new Login().configAccesoLoginUsuario();
                            break;
                case 1048: JOptionPane.showMessageDialog(null, "Debe ingresar todos los campos", "Registros", JOptionPane.ERROR_MESSAGE); 
                           break;
                case 1062: JOptionPane.showMessageDialog(null, "Persona ya registrada", "Registros", JOptionPane.ERROR_MESSAGE); 
                           break;
                case 1406: JOptionPane.showMessageDialog(null, "Datos exceden la longitud máxima permitida", "Registros", JOptionPane.ERROR_MESSAGE); 
                           break;  
                default: JOptionPane.showMessageDialog(null, "Error desconocido. Contacte al Administrador: " + resultado, "Registros", JOptionPane.ERROR_MESSAGE); 
                           break;
            }*/
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this.jTextFieldRut, "Ingrese el rut Correctamente","Registros",JOptionPane.WARNING_MESSAGE);
            this.jTextFieldRut.requestFocus();
        }
        catch(NullPointerException e)
        {
            JOptionPane.showMessageDialog(this.jTextFieldRut, "Debe seleccionar una Fecha Valida","Registros",JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private boolean validarFormularioRegistroUsuarios(){
        int validaciones = 0; 
        if(this.jTextFieldUsuario.getText().trim().isEmpty())
        {
            this.jTextFieldUsuario.setBackground(Color.cyan);
            validaciones++;
        }
        else{
            this.jTextFieldUsuario.setBackground(Color.black);
        }
        if (! validarContraseñaLetrasyNumeros()) 
        {
            this.jPasswordFieldContraseña.setBackground(Color.cyan);
            this.jPasswordFieldConfContraseña.setBackground(Color.cyan);
            validaciones++;
        }
        else{
            this.jPasswordFieldContraseña.setBackground(Color.black);
            this.jPasswordFieldConfContraseña.setBackground(Color.black);
        }
        if(! validarRut())
        {
            this.jTextFieldRut.setBackground(Color.cyan);
            validaciones++;
        }
        else{
            this.jTextFieldRut.setBackground(Color.black);
        }
        if(this.jTextFieldNombre.getText().trim().isEmpty())
        {
            this.jTextFieldNombre.setBackground(Color.cyan);
            validaciones++;
        }
        else{
            this.jTextFieldNombre.setBackground(Color.black);
        }
        if(! validarEmail(this.jTextFieldEmail.getText().trim()))
        {
            this.jTextFieldEmail.setBackground(Color.cyan);
            validaciones++;
        }
        else{
            this.jTextFieldEmail.setBackground(Color.black);
        }
        return validaciones == 0;
    }
    
    private void registrarUsuarios(){
        if (validarFormularioRegistroUsuarios())
        {
            registrarUser();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los valores que se indican...", "Registro CINEDEMARK", JOptionPane.WARNING_MESSAGE);
            this.jTextFieldUsuario.requestFocus();
        }
    }
    
    private boolean validarContraseñaLetrasyNumeros(){
        char[] Contraseña = this.jPasswordFieldContraseña.getPassword();
        if(Contraseña.length >=6)
        { 
            int numeros = 0; 
            int letras = 0;
            
            for(char x=0; x<Contraseña.length; x++)
            { 
                if((Contraseña[x] >47) && Contraseña[x]<58)
                { 
                    numeros++; 
                } 
            }
            for(char x=0; x<Contraseña.length; x++)
            { 
                if((Contraseña[x] >64) && Contraseña[x]<123)
                { 
                    letras++; 
                } 
            }
            if(numeros>0 && letras>0)
            { 
                jlblEstadoContraseña.setForeground(Color.white);
                jlblEstadoContraseña.setText("Su contraseña es Segura.");
                return true;
            }
            else
            { 
                jlblEstadoContraseña.setForeground(Color.yellow);
                jlblEstadoContraseña.setText("inserte letras y numeros.");
                return false;
            } 
        }
        else
        { 
            jlblEstadoContraseña.setForeground(Color.orange);
            jlblEstadoContraseña.setText("minimo 6 caracteres");
            return false;
        }
    }
    
    private boolean validarRut(){
        try
        {
            String rut = this.jTextFieldRut.getText();
            String[] rut_dv = rut.split("-");
            if (rut_dv.length == 2)
            {
                int rutValor = Integer.parseInt(rut_dv[0]);
                String DV = rut_dv[1].substring(0).toUpperCase();
                char dv = DV.charAt(0);
            
                // Validamos que sea un rut valido según la norma
                int m = 0, s = 1;
                for (; rutValor != 0; rutValor /= 10)
                {
                    s = (s + rutValor % 10 * (9 - m++ % 6)) % 11;
                }
            
                return dv == (char) (s != 0 ? s + 47 : 75);    
            }
            return false;
        }
        catch(NumberFormatException e)
        {
            return false;
        }
        
    }
    
    public void configAccesoRegistro(){
        RegistrarUsuario r = new RegistrarUsuario();
        r.setVisible(true);
        r.setLocationRelativeTo(null);
        r.setTitle("Registrar Usuario CINEDEMARK");
        r.jTextFieldUsuario.requestFocus();
        r.setResizable(false);
    }
    
    private void ReestablecerFormularioRegistroDeUsuario(){
    jPasswordFieldConfContraseña.setText(null);
    jPasswordFieldContraseña.setText(null);
    jTextFieldUsuario.setText(null);
    jTextFieldNombre.setText(null);
    jTextFieldRut.setText(null);
    jTextFieldEmail.setText(null);
    jlblEstadoContraseña.setText(" ");
    jlblEstadoContraseñasIguales.setText(" ");
    jlblEstadoRut.setText(" ");
    jLabelValidarEmail.setText(" ");
    jPasswordFieldConfContraseña.setBackground(Color.black);
    jPasswordFieldContraseña.setBackground(Color.black);
    jTextFieldUsuario.setBackground(Color.black);
    jTextFieldNombre.setBackground(Color.black);
    jTextFieldRut.setBackground(Color.black);
    jTextFieldEmail.setBackground(Color.black);
    }
    
    private boolean validarEmail(String email){
        String PATTERN_EMAIL = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        // Compiles the given regular expression into a pattern.
        Pattern pattern = Pattern.compile(PATTERN_EMAIL);
 
        // Match the given input against this pattern
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelValidarEmail;
    private javax.swing.JPasswordField jPasswordFieldConfContraseña;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldRut;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel jlblEstadoContraseña;
    private javax.swing.JLabel jlblEstadoContraseñasIguales;
    private javax.swing.JLabel jlblEstadoRut;
    // End of variables declaration//GEN-END:variables
}
